CERT_SERVER_IMAGE: 'openebl/cert_server:latest'
DATABASE_HOST: 'openebl-dev.gogoopenebl.us-east-1.rds.amazonaws.com'
DATABASE_PORT: '5432'
DATABASE_NAME: 'devbxebl_cert_server'
DATABASE_USER: 'openebladmin'
DATABASE_PASSWORD: 'xxxxxxxx'
DATABASE_POOL_SIZE: 5
DATABASE_SSLMODE: disable
OTLP_ENDPOINT: '{{ ansible_host }}:4317'
RELAY_SERVER: 'ws://openebl_relay_server1:9001'
PRIVATE_ADDRESS: 'localhost:9100'
PUBLIC_ADDRESS: ':9101'
