---
- name: Create required path
  ansible.builtin.file:
    path: /opt/monitoring/promtail/
    state: directory
    owner: "{{ ansible_user }}"

- name: Create openebl promtail Docker Compose file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
  with_items:
    - { src: "./files/docker-compose-promtail.yml.j2", dest: "/opt/monitoring/docker-compose-promtail.yml" }
    - { src: "./files/promtail-config.yaml.j2", dest: "/opt/monitoring/promtail/promtail-config.yaml" }

- name: Deploy promtail
  community.docker.docker_compose_v2:
    project_src: "/opt/monitoring/"
    files:
      - docker-compose-promtail.yml
    state: present
    pull: true
    recreate: smart
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
