---
- name: Create required path
  ansible.builtin.file:
    path: /opt/openebl/
    state: directory
    mode: 0744

- name: Create openebl BU server Docker Compose file
  template:
    src: ./files/docker-compose-bu-server.yml.j2
    dest: /opt/openebl/docker-compose-bu-server.yml

- name: Deploy openebl BU server
  community.docker.docker_compose_v2:
    project_src: "/opt/openebl/"
    files:
      - docker-compose-bu-server.yml
    state: present
    pull: always
    recreate: always
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
