---
- name: Create required path
  ansible.builtin.file:
    path: /opt/openebl/
    state: directory
    mode: 0700
    owner: "{{ ansible_user }}"

- name: Create openebl relay server Docker Compose file
  template:
    src: ./files/docker-compose-relay-server.yml.j2
    dest: /opt/openebl/docker-compose-relay-server.yml
    owner: "{{ ansible_user }}"

- name: Deploy openebl relay server
  community.docker.docker_compose_v2:
    project_src: "/opt/openebl/"
    files:
      - docker-compose-relay-server.yml
    state: present
    pull: always
    recreate: always
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
