- name: Create required path
  ansible.builtin.file:
    path: /etc/docker/
    state: directory
    owner: "{{ ansible_user }}"
    group: root
    mode: 0744

- name: Configure Docker Daemon Logger
  template:
    src: ./files/daemon.json
    dest: /etc/docker/daemon.json
    owner: "{{ ansible_user }}"
    group: root
    mode: 0755

- name: Run apt update
  command: apt update
  when:
    - ansible_pkg_mgr == 'apt'

- name: Print ansible_pkg_mgr
  debug:
    var: ansible_pkg_mgr

- name: Install docker package (Debian based systems)
  ansible.builtin.package:
    name: docker.io
    state: present
  run_once: true
  when: ansible_pkg_mgr == 'apt'

- name: Install docker package (redhat based systems)
  ansible.builtin.package:
    name: docker
    state: present
  run_once: true
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

# - name: Install Docker Compose
#   ansible.builtin.package:
#     state: present
#     name:
#       - docker-compose-v2
#   run_once: true

- name: Reload Docker Daemon
  systemd:
    state: reloaded
    name: docker
  run_once: true

- name: Enable docker service
  ansible.builtin.service:
    name: docker
    enabled: yes
  run_once: true

- name: Install pip
  ansible.builtin.package:
    name: python3-pip
    state: present
  run_once: true

- name: Use docker without sudo
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install pip modules on target box
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker==6.1.3
    - docker-compose
  run_once: true
  when: ansible_pkg_mgr == 'apt'

- name: Install pip modules on target box
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
  run_once: true
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

- name: Install ctop
  get_url:
    url: https://github.com/bcicen/ctop/releases/download/v0.7.7/ctop-0.7.7-linux-amd64
    dest: /usr/local/bin/ctop
    mode: 0755
  run_once: true
