{
 "title": "Open eBL metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "BU Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request count by (http_method, http_route, http_status_code)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (http_method, http_route, http_status_code) (rate(bu_server_api_request_duration_count{}[$__rate_interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bu_server_api_request_duration P99 P95 P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(bu_server_api_request_duration_bucket[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bu_server_api_request_duration_bucket[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(bu_server_api_request_duration_bucket[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Relay Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "relay_server_event_read_count_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(relay_server_event_read_count_total) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "relay_server_connection_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(relay_server_connection_count) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "relay_server_read_count_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": " sum(relay_server_read_count_total) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "relay_server_send_count_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(relay_server_send_count_total) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "relay_server_read_event by client_id",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "count by (client_id) (relay_server_read_count_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}